//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalPointCPKiO.ModelEDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public int ID { get; set; }
        public int Post { get; set; }
        public string Surname { get; set; }
        public string Firstname { get; set; }
        public string Middlename { get; set; }
        public string FullName
        {
            get
            {
                return this.Surname + " " + this.Firstname + " " + this.Middlename;
            }
        }

        public string Login { get; set; }
        public string Password { get; set; }
        public System.DateTime LastVisit { get; set; }
        public string isVisit { get; set; }
        public string Image { get; set; }
    
        public virtual Roles Roles { get; set; }
    }
}
